version: "3"

services:
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        restart: unless-stopped
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        networks:
            - prometheus-cadvisor

    docker_state_exporter:
        image: karugaru/docker_state_exporter
        container_name: docker_state_exporter
        restart: unless-stopped
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
        networks:
            - prometheus-docker_state_exporter

    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node_exporter
        command:
            - --path.rootfs=/host
        pid: host
        restart: unless-stopped
        volumes:
            - /:/host:ro,rslave
        networks:
            - prometheus-node_exporter

    blackbox_exporter:
        image: quay.io/prometheus/blackbox-exporter:latest
        container_name: blackbox_exporter
        command:
            - --config.file=/config/blackbox.yaml
        restart: unless-stopped
        volumes:
            - ./blackbox_exporter/:/config
        networks:
            - prometheus-blackbox_exporter

    discourse_forward_proxy:
        image: nginx:latest
        container_name: discourse_forward_proxy
        restart: unless-stopped
        volumes:
            - ./discourse_forward_proxy/:/etc/nginx/conf.d
        networks:
            - prometheus-discourse_forward_proxy
            - discourse

    prometheus:
        depends_on:
            - cadvisor
            - node_exporter
            - discourse_forward_proxy
        image: prom/prometheus:latest
        restart: unless-stopped
        container_name: prometheus
        # uncomment only to access web interface for debug/testing
        #ports:
        #    - 9090:9090
        volumes:
            - ./prometheus:/app.cfg
            - ./prometheus/data:/prometheus
        networks:
            - prometheus-cadvisor
            - prometheus-docker_state_exporter
            - prometheus-node_exporter
            - prometheus-blackbox_exporter
            - prometheus-discourse_forward_proxy
            - grafana-prometheus
        command: >-
            --config.file=/app.cfg/prometheus.yaml
            --storage.tsdb.path=/prometheus
            --web.console.libraries=/usr/share/prometheus/console_libraries
            --web.console.templates=/usr/share/prometheus/consoles
            --storage.tsdb.retention.time=60d

    grafana:
        depends_on:
            - prometheus
        image: grafana/grafana:latest
        container_name: grafana
        restart: unless-stopped
        environment:
            GF_SECURITY_ADMIN_USER: ADMIN_USER_PLACEHOLDER
            GF_SECURITY_ADMIN_PASSWORD: ADMIN_PASS_PLACEHOLDER
        ports:
            # 8443 due to restriction on ports from cloudflare
            - 8443:3000
        volumes:
            - ./grafana:/etc/grafana
        networks:
            - grafana-prometheus
            - discourse

networks:
    grafana-prometheus:
        internal: true
    prometheus-cadvisor:
        internal: true
    prometheus-docker_state_exporter:
        internal: true
    prometheus-node_exporter:
        internal: true
    prometheus-blackbox_exporter:
        internal: true
    prometheus-discourse_forward_proxy:
        internal: true
    discourse:
        external: true
