global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'prometheus:9090'
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'cadvisor:8080'
  - job_name: docker_state_exporter
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'docker_state_exporter:8080'
  - job_name: node_exporter
    static_configs:
      - targets:
        - 'node_exporter:9100'
  - job_name: discourse_exporter
    #scheme: https
    #tls_config:
    #  insecure_skip_verify: true
    static_configs:
      - targets:
        - 'discourse_app:80'
