global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'prometheus:9090'
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'cadvisor:8080'
  - job_name: docker_state_exporter
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'docker_state_exporter:8080'
  - job_name: node_exporter
    static_configs:
      - targets:
        - 'node_exporter:9100'
  - job_name: blackbox_exporter
    metrics_path: /probe
    params:
      module: [http_2xx, https_2xx]
    static_configs:
      - targets:
        - 'https://netgamers.it'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox_exporter:9115'
  - job_name: discourse_exporter_proxy
    scheme: http
    static_configs:
      - targets:
        - 'discourse_forward_proxy:8080'
