{
 "title": "Discourse",
 "description": "Official Dashboard Used by the Prometheus Discourse plugin",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "query": "label_values(discourse_page_views,job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Sidekiq Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(discourse_rss{type='sidekiq',job='$site'})"
    }
   ]
  },
  {
   "title": "Web Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(discourse_rss{type='web',job='$site'})"
    }
   ]
  },
  {
   "title": "Sidekiq Queued",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(discourse_sidekiq_jobs_enqueued)"
    }
   ]
  },
  {
   "title": "Sidekiq Jobs / Hr",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(discourse_sidekiq_job_count{job=\"discourse_exporter_proxy\"}[60m]) * 60 * 60) by (job)"
    }
   ]
  },
  {
   "title": "Domain Uptime",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "up{instance=\"https://netgamers.it\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Uptime",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "discourse_redis_primary_available * 100",
     "legendFormat": "Primary"
    }
   ]
  },
  {
   "title": "Redis Uptime",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "discourse_redis_primary_available * 100",
     "legendFormat": "Primary"
    }
   ]
  },
  {
   "title": "Latest Page Median Performance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(discourse_http_duration_seconds{quantile=\"0.5\",action=\"latest\",controller=\"list\",job=\"$site\"}) * 1000",
     "legendFormat": "Total(ms)"
    },
    {
     "expr": "avg(discourse_http_redis_duration_seconds{quantile=\"0.5\",action=\"latest\",controller=\"list\",job=\"$site\"}) * 1000",
     "legendFormat": "Redis"
    },
    {
     "expr": "avg(discourse_http_sql_duration_seconds{quantile=\"0.5\",action=\"latest\",controller=\"list\",job=\"$site\"}) * 1000",
     "legendFormat": "SQL"
    }
   ]
  },
  {
   "title": "Topic Show Median Page Performance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(discourse_http_duration_seconds{quantile=\"0.5\",action=\"show\",controller=\"topics\",job=\"$site\"}) * 1000",
     "legendFormat": "Total(ms)"
    },
    {
     "expr": "avg(discourse_http_redis_duration_seconds{quantile=\"0.5\",action=\"show\",controller=\"topics\",job=\"$site\"}) * 1000",
     "legendFormat": "Redis"
    },
    {
     "expr": "avg(discourse_http_sql_duration_seconds{quantile=\"0.5\",action=\"show\",controller=\"topics\",job=\"$site\"}) * 1000",
     "legendFormat": "SQL"
    }
   ]
  },
  {
   "title": "Latest 99th percentile Performance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(discourse_http_duration_seconds{quantile=\"0.99\",action=\"latest\",controller=\"list\",job=\"$site\"}) * 1000",
     "legendFormat": "Total(ms)"
    },
    {
     "expr": "avg(discourse_http_redis_duration_seconds{quantile=\"0.99\",action=\"latest\",controller=\"list\",job=\"$site\"}) * 1000",
     "legendFormat": "Redis"
    },
    {
     "expr": "avg(discourse_http_sql_duration_seconds{quantile=\"0.99\",action=\"latest\",controller=\"list\",job=\"$site\"}) * 1000",
     "legendFormat": "SQL"
    }
   ]
  },
  {
   "title": "Topic Page 99th Percentile Performance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(discourse_http_duration_seconds{quantile=\"0.99\",action=\"show\",controller=\"topics\",job=\"$site\"}) * 1000",
     "legendFormat": "Total(ms)"
    },
    {
     "expr": "avg(discourse_http_redis_duration_seconds{quantile=\"0.99\",action=\"show\",controller=\"topics\",job=\"$site\"}) * 1000",
     "legendFormat": "Redis"
    },
    {
     "expr": "avg(discourse_http_sql_duration_seconds{quantile=\"0.99\",action=\"show\",controller=\"topics\",job=\"$site\"}) * 1000",
     "legendFormat": "SQL"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(discourse_http_requests[1m]))",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Error HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(increase(discourse_http_requests{status=~\"^[45].*\"}[1m])) / sum(increase(discourse_http_requests[1m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Page Views / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(discourse_page_views{job=\"$site\"}[5m])) by (type,device)",
     "legendFormat": "{{device}} - {{type}}"
    }
   ]
  },
  {
   "title": "Active Web Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(discourse_active_app_reqs{job=\"$site\"}) by (job)",
     "legendFormat": "Active Requests"
    },
    {
     "expr": "sum(discourse_queued_app_reqs{job=\"$site\"}) by (job)",
     "legendFormat": "Queued Requests"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"app\"}[5m])",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"app\"}",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Object Allocation Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(discourse_total_allocated_objects{job=\"$site\"}[5m])) by(type,job)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Ruby Heap Stats (Webs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(discourse_heap_live_slots{job=\"$site\",type=\"web\"}) by (type, instance)",
     "legendFormat": "{{instance}} max live"
    },
    {
     "expr": "min(discourse_heap_free_slots{job=\"$site\",type=\"web\"}) by (instance, type)",
     "legendFormat": "{{instance}} min free"
    }
   ]
  },
  {
   "title": "Max RSS per Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(discourse_rss{job=\"$site\"}) by (job,instance,type)",
     "legendFormat": "{{type}} {{instance}}"
    }
   ]
  },
  {
   "title": "V8 used memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(discourse_v8_used_heap_size{job=\"$site\"}) by (type, instance)",
     "legendFormat": "{{type}} {{instance}}"
    }
   ]
  },
  {
   "title": "Sidekiq Job Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(discourse_sidekiq_job_duration_seconds{job=\"$site\"}[5m])) by (job_name)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Scheduled Job Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(discourse_scheduled_job_duration_seconds{job=\"$site\"}[5m])) by (job_name)",
     "legendFormat": "{{job_name}}"
    }
   ]
  }
 ]
}